version: "3.5"

services:
  pyapp:
    image: mcr.microsoft.com/devcontainers/python:0-3.11-bullseye
    volumes:
        - ..:/workspaces/DevContainer_Py_Mongodb_MongoExpress:cached     # .. => upper level dir, it is dev-con-study dir. 
    # network_mode: service:MONGO
    networks:
      - MONGONET
    command: sleep infinity

  mongobase:
    image: mongo:latest
    container_name: mongobase
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - MONGONET
    volumes:
      - type: volume
        source: MONGO_DATA_BASE
        target: /data/db
      - type: volume
        source: MONGO_CONFIG_BASE
        target: /data/configdb
  mongo-expressbase:
    image: mongo-express:latest
    container_name: mongo-expressbase
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongobase
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - MONGONET
    depends_on:
      - mongobase

networks:
  MONGONET:
    name: MONGONET

volumes:
  MONGO_DATA_BASE:
    name: MONGO_DATA_BASE
  MONGO_CONFIG_BASE:
    name: MONGO_CONFIG_BASE