FROM mcr.microsoft.com/devcontainers/python:0-3.11-bullseye
# TODO 
# 1. install ipykernel for notebook
# 2. install pip install langchain  openai
# 3. Logging/Tracing https://python.langchain.com/en/latest/tracing.html