version: "3.5"

services:
  hsi-pyapp:
    image: mcr.microsoft.com/devcontainers/python:0-3.11-bullseye
    volumes:
        - ..:/workspaces/HSI_Future_RL:cached     # .. => upper level dir, it is dev-con-study dir. 
    # network_mode: service:MONGO
    networks:
      - HSIMONGO
    command: sleep infinity

  hsi-mongo:
    image: mongo:latest
    container_name: hsi-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - HSIMONGO
    volumes:
      - type: volume
        source: HSI_MONGO_DATA
        target: /data/db
      - type: volume
        source: HSI_MONGO_CONFIG
        target: /data/configdb
  hsi-mongo-express:
    image: mongo-express:latest
    container_name: hsi-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: hsimongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - HSIMONGO
    depends_on:
      - hsi-mongo

networks:
  HSIMONGO:
    name: HSIMONGO

volumes:
  HSI_MONGO_DATA:
    name: HSI_MONGO_DATA
  HSI_MONGO_CONFIG:
    name: HSI_MONGO_CONFIG